In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [2]:
dataset=pd.read_csv('/home/ubuntu/Downloads/educationcompany/Leads.csv')

In [3]:
dataset.head(5)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [4]:
# finding the missing values
dataset.isna().sum().sort_values(ascending=False)

Lead Quality                                     4767
Asymmetrique Activity Index                      4218
Asymmetrique Profile Score                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Index                       4218
Tags                                             3353
Lead Profile                                     2709
What matters most to you in choosing a course    2709
What is your current occupation                  2690
Country                                          2461
How did you hear about X Education               2207
Specialization                                   1438
City                                             1420
Page Views Per Visit                              137
TotalVisits                                       137
Last Activity                                     103
Lead Source                                        36
Receive More Updates About Our Courses              0
I agree to pay the amount through cheque            0
Get updates on DM Content                           0
Update me on Supply Chain Content                   0
A free copy of Mastering The Interview              0
Prospect ID                                         0
Newspaper Article                                   0
Through Recommendations                             0
Digital Advertisement                               0
Newspaper                                           0
X Education Forums                                  0
Lead Number                                         0
Magazine                                            0
Search                                              0
Total Time Spent on Website                         0
Converted                                           0
Do Not Call                                         0
Do Not Email                                        0
Lead Origin                                         0
Last Notable Activity                               0
dtype: int64

In [5]:
# deleting the columns which is having more missing values
dataset.drop(columns=['Lead Quality','Asymmetrique Activity Index',
                      'Asymmetrique Profile Score','Asymmetrique Activity Score',
                      'Asymmetrique Profile Index','Prospect ID','Lead Number'],inplace=True)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 30 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Lead Origin                                    9240 non-null   object
 1   Lead Source                                    9204 non-null   object
 2   Do Not Email                                   9240 non-null   object
 3   Do Not Call                                    9240 non-null   object
 4   Converted                                      9240 non-null   int64
 5   TotalVisits                                    9103 non-null   float64
 6   Total Time Spent on Website                    9240 non-null   int64
 7   Page Views Per Visit                           9103 non-null   float64
 8   Last Activity                                  9137 non-null   object
 9   Country                                        6779 non-null   object
 10  Specialization                                 7802 non-null   object
 11  How did you hear about X Education             7033 non-null   object
 12  What is your current occupation                6550 non-null   object
 13  What matters most to you in choosing a course  6531 non-null   object
 14  Search                                         9240 non-null   object
 15  Magazine                                       9240 non-null   object
 16  Newspaper Article                              9240 non-null   object
 17  X Education Forums                             9240 non-null   object
 18  Newspaper                                      9240 non-null   object
 19  Digital Advertisement                          9240 non-null   object
 20  Through Recommendations                        9240 non-null   object
 21  Receive More Updates About Our Courses         9240 non-null   object
 22  Tags                                           5887 non-null   object
 23  Update me on Supply Chain Content              9240 non-null   object
 24  Get updates on DM Content                      9240 non-null   object
 25  Lead Profile                                   6531 non-null   object
 26  City                                           7820 non-null   object
 27  I agree to pay the amount through cheque       9240 non-null   object
 28  A free copy of Mastering The Interview         9240 non-null   object
 29  Last Notable Activity                          9240 non-null   object
dtypes: float64(2), int64(2), object(26)
memory usage: 2.1+ MB

In [7]:
# finding the unique values in categorical columns
categ=dataset.select_dtypes('object').columns

for i in categ:
    print(dataset[i].value_counts())
    print()

Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: Lead Origin, dtype: int64

Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: Lead Source, dtype: int64

No     8506
Yes     734
Name: Do Not Email, dtype: int64

No     9238
Yes       2
Name: Do Not Call, dtype: int64

Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: Last Activity, dtype: int64

India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Hong Kong                  7
Bahrain                    7
Oman                       6
France                     6
unknown                    5
South Africa               4
Nigeria                    4
Germany                    4
Kuwait                     4
Canada                     4
Sweden                     3
China                      2
Asia/Pacific Region        2
Uganda                     2
Bangladesh                 2
Italy                      2
Belgium                    2
Netherlands                2
Ghana                      2
Philippines                2
Russia                     1
Switzerland                1
Vietnam                    1
Denmark                    1
Tanzania                   1
Liberia                    1
Malaysia                   1
Kenya                      1
Sri Lanka                  1
Indonesia                  1
Name: Country, dtype: int64

Select                               1942
Finance Management                    976
Human Resource Management             848
Marketing Management                  838
Operations Management                 503
Business Administration               403
IT Projects Management                366
Supply Chain Management               349
Banking, Investment And Insurance     338
Travel and Tourism                    203
Media and Advertising                 203
International Business                178
Healthcare Management                 159
Hospitality Management                114
E-COMMERCE                            112
Retail Management                     100
Rural and Agribusiness                 73
E-Business                             57
Services Excellence                    40
Name: Specialization, dtype: int64

Select                   5043
Online Search             808
Word Of Mouth             348
Student of SomeSchool     310
Other                     186
Multiple Sources          152
Advertisements             70
Social Media               67
Email                      26
SMS                        23
Name: How did you hear about X Education, dtype: int64

Unemployed              5600
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: What is your current occupation, dtype: int64

Better Career Prospects      6528
Flexibility & Convenience       2
Other                           1
Name: What matters most to you in choosing a course, dtype: int64

No     9226
Yes      14
Name: Search, dtype: int64

No    9240
Name: Magazine, dtype: int64

No     9238
Yes       2
Name: Newspaper Article, dtype: int64

No     9239
Yes       1
Name: X Education Forums, dtype: int64

No     9239
Yes       1
Name: Newspaper, dtype: int64

No     9236
Yes       4
Name: Digital Advertisement, dtype: int64

No     9233
Yes       7
Name: Through Recommendations, dtype: int64

No    9240
Name: Receive More Updates About Our Courses, dtype: int64

Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: Tags, dtype: int64

No    9240
Name: Update me on Supply Chain Content, dtype: int64

No    9240
Name: Get updates on DM Content, dtype: int64

Select                         4146
Potential Lead                 1613
Other Leads                     487
Student of SomeSchool           241
Lateral Student                  24
Dual Specialization Student      20
Name: Lead Profile, dtype: int64

Mumbai                         3222
Select                         2249
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: City, dtype: int64

No    9240
Name: I agree to pay the amount through cheque, dtype: int64

No     6352
Yes    2888
Name: A free copy of Mastering The Interview, dtype: int64

Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: Last Notable Activity, dtype: int64

In [8]:
dataset=dataset.replace('google','Google')
dataset=dataset.replace('Want to take admission but has financial problems','Shall take in the next coming month')
dataset=dataset.replace('Shall take in the next coming month','Interested in Next batch')
dataset=dataset.replace('Still Thinking','In confusion whether part time or DLP')

In [9]:
# dropping skewed columns
dataset.drop(columns=['What matters most to you in choosing a course','Search',
                      'Magazine','Newspaper Article','X Education Forums','Newspaper',
                      'Digital Advertisement','Through Recommendations','Receive More Updates About Our Courses',
                      'Update me on Supply Chain Content','Update me on Supply Chain Content',
                      'I agree to pay the amount through cheque','Do Not Call',
                      'What matters most to you in choosing a course','Get updates on DM Content'],inplace=True)

In [10]:
# replacing the null values with NaN
dataset=dataset.replace(['unknown','Select'],np.NaN)

In [11]:
categ=dataset.select_dtypes('object').columns

for i in categ:
    print(dataset[i].value_counts())
    print()

Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: Lead Origin, dtype: int64

Google               2873
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
bing                    6
Click2call              4
Social Media            2
Live Chat               2
Press_Release           2
Pay per Click Ads       1
blog                    1
WeLearn                 1
welearnblog_Home        1
youtubechannel          1
testone                 1
NC_EDM                  1
Name: Lead Source, dtype: int64

No     8506
Yes     734
Name: Do Not Email, dtype: int64

Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: Last Activity, dtype: int64

India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Bahrain                    7
Hong Kong                  7
Oman                       6
France                     6
Kuwait                     4
South Africa               4
Canada                     4
Nigeria                    4
Germany                    4
Sweden                     3
Bangladesh                 2
Asia/Pacific Region        2
Philippines                2
Italy                      2
Uganda                     2
Netherlands                2
China                      2
Belgium                    2
Ghana                      2
Russia                     1
Kenya                      1
Sri Lanka                  1
Tanzania                   1
Malaysia                   1
Liberia                    1
Switzerland                1
Denmark                    1
Vietnam                    1
Indonesia                  1
Name: Country, dtype: int64

Finance Management                   976
Human Resource Management            848
Marketing Management                 838
Operations Management                503
Business Administration              403
IT Projects Management               366
Supply Chain Management              349
Banking, Investment And Insurance    338
Travel and Tourism                   203
Media and Advertising                203
International Business               178
Healthcare Management                159
Hospitality Management               114
E-COMMERCE                           112
Retail Management                    100
Rural and Agribusiness                73
E-Business                            57
Services Excellence                   40
Name: Specialization, dtype: int64

Online Search            808
Word Of Mouth            348
Student of SomeSchool    310
Other                    186
Multiple Sources         152
Advertisements            70
Social Media              67
Email                     26
SMS                       23
Name: How did you hear about X Education, dtype: int64

Unemployed              5600
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: What is your current occupation, dtype: int64

Will revert after reading the email      2072
Ringing                                  1203
Interested in other courses               513
Already a student                         465
Closed by Horizzon                        358
switched off                              240
Busy                                      186
Lost to EINS                              175
Not doing further education               145
Interested  in full time MBA              117
Graduation in progress                    111
invalid number                             83
Diploma holder (Not Eligible)              63
wrong number given                         47
opp hangup                                 33
number not provided                        27
Interested in Next batch                   13
in touch with EINS                         12
In confusion whether part time or DLP      11
Lost to Others                              7
Lateral student                             3
University not recognized                   2
Recognition issue (DEC approval)            1
Name: Tags, dtype: int64

Potential Lead                 1613
Other Leads                     487
Student of SomeSchool           241
Lateral Student                  24
Dual Specialization Student      20
Name: Lead Profile, dtype: int64

Mumbai                         3222
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: City, dtype: int64

No     6352
Yes    2888
Name: A free copy of Mastering The Interview, dtype: int64

Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: Last Notable Activity, dtype: int64

In [12]:
categ=dataset.select_dtypes('object').columns

In [13]:
# replacing  the missing values of categorical and numerical columns
for i in categ:
    dataset[i].fillna(dataset[i].mode()[0],inplace=True)

In [14]:
dataset.isna().sum().sort_values(ascending=False)

TotalVisits                               137
Page Views Per Visit                      137
Lead Origin                                 0
How did you hear about X Education          0
A free copy of Mastering The Interview      0
City                                        0
Lead Profile                                0
Tags                                        0
What is your current occupation             0
Country                                     0
Specialization                              0
Lead Source                                 0
Last Activity                               0
Total Time Spent on Website                 0
Converted                                   0
Do Not Email                                0
Last Notable Activity                       0
dtype: int64

In [15]:
# numerical columns
numeric=dataset.select_dtypes('number')
numeric.isna().sum()

Converted                        0
TotalVisits                    137
Total Time Spent on Website      0
Page Views Per Visit           137
dtype: int64

In [16]:
# replacing the missing values of numerical columns
for j in numeric:
    dataset[j].fillna(dataset[j].median(),inplace=True)

In [17]:
numeric.isna().sum()

Converted                      0
TotalVisits                    0
Total Time Spent on Website    0
Page Views Per Visit           0
dtype: int64

In [18]:
categorical_features = dataset.select_dtypes(include=[np.object])

In [19]:
categorical_features.nunique()

Lead Origin                                5
Lead Source                               20
Do Not Email                               2
Last Activity                             17
Country                                   37
Specialization                            18
How did you hear about X Education         9
What is your current occupation            6
Tags                                      23
Lead Profile                               5
City                                       6
A free copy of Mastering The Interview     2
Last Notable Activity                     16
dtype: int64

In [20]:
# finding and applying label encoder to the  columns which is having two unique values
cat = []
for i in categorical_features.columns:
    if categorical_features[i].nunique()==2:
        cat.append(i)
print(cat)

['Do Not Email', 'A free copy of Mastering The Interview']

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [22]:
for i in cat:
    dataset[i]= encoder.fit_transform(dataset[i])

In [23]:
dataset.head(3)

,Lead Origin,Lead Source,Do Not Email,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,Specialization,How did you hear about X Education,What is your current occupation,Tags,Lead Profile,City,A free copy of Mastering The Interview,Last Notable Activity
0,API,Olark Chat,0,0,0.0,0,0.0,Page Visited on Website,India,Finance Management,Online Search,Unemployed,Interested in other courses,Potential Lead,Mumbai,0,Modified
1,API,Organic Search,0,0,5.0,674,2.5,Email Opened,India,Finance Management,Online Search,Unemployed,Ringing,Potential Lead,Mumbai,0,Email Opened
2,Landing Page Submission,Direct Traffic,0,1,2.0,1532,2.0,Email Opened,India,Business Administration,Online Search,Student,Will revert after reading the email,Potential Lead,Mumbai,1,Email Opened

In [24]:
# dropping columns which are not important
dataset.drop(columns=['Country','City'],inplace=True)

In [25]:
categorical_features = dataset.select_dtypes(include=[np.object]).columns

In [26]:
#  applying the one-hot encoding for the columns which are having more than 2 unique values
dataset=pd.get_dummies(data=dataset,columns=categorical_features,drop_first=True)

In [27]:
dataset

,Do Not Email,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,A free copy of Mastering The Interview,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,...,Last Notable Activity_Form Submitted on Website,Last Notable Activity_Had a Phone Conversation,Last Notable Activity_Modified,Last Notable Activity_Olark Chat Conversation,Last Notable Activity_Page Visited on Website,Last Notable Activity_Resubscribed to emails,Last Notable Activity_SMS Sent,Last Notable Activity_Unreachable,Last Notable Activity_Unsubscribed,Last Notable Activity_View in browser link Clicked
0,0,0,0.0,0,0.00,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,5.0,674,2.50,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,2.0,1532,2.00,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1.0,305,1.00,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,1,2.0,1428,1.00,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,1,1,8.0,1845,2.67,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9236,0,0,2.0,238,2.00,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9237,1,0,2.0,199,2.00,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9238,0,1,3.0,499,3.00,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9239,0,1,6.0,1279,3.00,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [28]:
# independent variables
x=dataset.drop(columns=['Converted'])

In [29]:
x.head()

,Do Not Email,TotalVisits,Total Time Spent on Website,Page Views Per Visit,A free copy of Mastering The Interview,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,...,Last Notable Activity_Form Submitted on Website,Last Notable Activity_Had a Phone Conversation,Last Notable Activity_Modified,Last Notable Activity_Olark Chat Conversation,Last Notable Activity_Page Visited on Website,Last Notable Activity_Resubscribed to emails,Last Notable Activity_SMS Sent,Last Notable Activity_Unreachable,Last Notable Activity_Unsubscribed,Last Notable Activity_View in browser link Clicked
0,0,0.0,0,0.0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,5.0,674,2.5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,2.0,1532,2.0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,1.0,305,1.0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,0,2.0,1428,1.0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [30]:
# target variable
y=dataset['Converted']

In [31]:

from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=25)

In [33]:
x_train.columns

Index(['Do Not Email', 'TotalVisits', 'Total Time Spent on Website',
       'Page Views Per Visit', 'A free copy of Mastering The Interview',
       'Lead Origin_Landing Page Submission', 'Lead Origin_Lead Add Form',
       'Lead Origin_Lead Import', 'Lead Origin_Quick Add Form',
       'Lead Source_Direct Traffic',
       ...
       'Last Notable Activity_Form Submitted on Website',
       'Last Notable Activity_Had a Phone Conversation',
       'Last Notable Activity_Modified',
       'Last Notable Activity_Olark Chat Conversation',
       'Last Notable Activity_Page Visited on Website',
       'Last Notable Activity_Resubscribed to emails',
       'Last Notable Activity_SMS Sent', 'Last Notable Activity_Unreachable',
       'Last Notable Activity_Unsubscribed',
       'Last Notable Activity_View in browser link Clicked'],
      dtype='object', length=115)

In [34]:
x_train

,Do Not Email,TotalVisits,Total Time Spent on Website,Page Views Per Visit,A free copy of Mastering The Interview,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,...,Last Notable Activity_Form Submitted on Website,Last Notable Activity_Had a Phone Conversation,Last Notable Activity_Modified,Last Notable Activity_Olark Chat Conversation,Last Notable Activity_Page Visited on Website,Last Notable Activity_Resubscribed to emails,Last Notable Activity_SMS Sent,Last Notable Activity_Unreachable,Last Notable Activity_Unsubscribed,Last Notable Activity_View in browser link Clicked
4210,0,4.0,409,4.0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3797,0,4.0,374,4.0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9220,0,5.0,20,2.5,1,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
891,0,4.0,453,2.0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
126,0,1.0,127,1.0,1,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0,4.0,287,4.0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8447,0,3.0,127,1.5,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2934,0,2.0,350,2.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6618,0,0.0,0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8510,0,4.0,1840,4.0,1,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [35]:
x_train.mean()

Do Not Email                                            0.079221
TotalVisits                                             3.441558
Total Time Spent on Website                           490.595527
Page Views Per Visit                                    2.356091
A free copy of Mastering The Interview                  0.314719
                                                         ...
Last Notable Activity_Resubscribed to emails            0.000000
Last Notable Activity_SMS Sent                          0.241991
Last Notable Activity_Unreachable                       0.003030
Last Notable Activity_Unsubscribed                      0.005195
Last Notable Activity_View in browser link Clicked      0.000144
Length: 115, dtype: float64

In [36]:
x_train.std()

Do Not Email                                            0.270103
TotalVisits                                             4.902408
Total Time Spent on Website                           548.647589
Page Views Per Visit                                    2.061836
A free copy of Mastering The Interview                  0.464437
                                                         ...
Last Notable Activity_Resubscribed to emails            0.000000
Last Notable Activity_SMS Sent                          0.428320
Last Notable Activity_Unreachable                       0.054969
Last Notable Activity_Unsubscribed                      0.071893
Last Notable Activity_View in browser link Clicked      0.012012
Length: 115, dtype: float64

In [37]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

In [38]:
x_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']] = scaler.fit_transform(x_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']])
x_test[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']] = scaler.transform(x_test[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']])

In [39]:
x_train

,Do Not Email,TotalVisits,Total Time Spent on Website,Page Views Per Visit,A free copy of Mastering The Interview,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Origin_Lead Import,Lead Origin_Quick Add Form,Lead Source_Direct Traffic,...,Last Notable Activity_Form Submitted on Website,Last Notable Activity_Had a Phone Conversation,Last Notable Activity_Modified,Last Notable Activity_Olark Chat Conversation,Last Notable Activity_Page Visited on Website,Last Notable Activity_Resubscribed to emails,Last Notable Activity_SMS Sent,Last Notable Activity_Unreachable,Last Notable Activity_Unsubscribed,Last Notable Activity_View in browser link Clicked
4210,0,0.113920,-0.148732,0.797361,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3797,0,0.113920,-0.212530,0.797361,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9220,0,0.317916,-0.857799,0.069802,1,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
891,0,0.113920,-0.068529,-0.172718,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
126,0,-0.498068,-0.662760,-0.657758,1,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0,0.113920,-0.371113,0.797361,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8447,0,-0.090076,-0.662760,-0.415238,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2934,0,-0.294072,-0.256277,-0.172718,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6618,0,-0.702065,-0.894255,-1.142797,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8510,0,0.113920,2.459688,0.797361,1,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [40]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier()
#  import rfe model for feature selection
from sklearn.feature_selection import RFE

rfe= RFE(rf_model,n_features_to_select=10)

rfe.fit(x_train,y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=10)

In [41]:
pd.DataFrame(zip(x_train.columns,rfe.support_,rfe.ranking_))

                                                     0      1    2
0                                         Do Not Email  False   12
1                                          TotalVisits   True    1
2                          Total Time Spent on Website   True    1
3                                 Page Views Per Visit   True    1
4               A free copy of Mastering The Interview  False   13
..                                                 ...    ...  ...
110       Last Notable Activity_Resubscribed to emails  False  103
111                     Last Notable Activity_SMS Sent   True    1
112                  Last Notable Activity_Unreachable  False   70
113                 Last Notable Activity_Unsubscribed  False   76
114  Last Notable Activity_View in browser link Cli...  False   99

[115 rows x 3 columns]

In [42]:
top_10_col=x_train.columns[rfe.support_]
top_10_col

Index(['TotalVisits', 'Total Time Spent on Website', 'Page Views Per Visit',
       'Lead Origin_Lead Add Form', 'Last Activity_SMS Sent',
       'What is your current occupation_Working Professional',
       'Tags_Closed by Horizzon', 'Tags_Ringing',
       'Tags_Will revert after reading the email',
       'Last Notable Activity_SMS Sent'],
      dtype='object')

In [43]:
x_train = x_train[top_10_col]
x_train

,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Lead Origin_Lead Add Form,Last Activity_SMS Sent,What is your current occupation_Working Professional,Tags_Closed by Horizzon,Tags_Ringing,Tags_Will revert after reading the email,Last Notable Activity_SMS Sent
4210,0.113920,-0.148732,0.797361,0,0,0,0,0,1,0
3797,0.113920,-0.212530,0.797361,0,0,0,0,0,0,0
9220,0.317916,-0.857799,0.069802,0,1,0,0,0,0,0
891,0.113920,-0.068529,-0.172718,0,0,0,0,0,1,0
126,-0.498068,-0.662760,-0.657758,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1175,0.113920,-0.371113,0.797361,0,1,0,0,1,0,0
8447,-0.090076,-0.662760,-0.415238,0,0,0,0,0,0,0
2934,-0.294072,-0.256277,-0.172718,0,0,0,0,0,1,0
6618,-0.702065,-0.894255,-1.142797,0,0,0,0,0,1,0
8510,0.113920,2.459688,0.797361,0,1,0,0,0,0,1

In [44]:
x_test = x_test[top_10_col]
x_test

,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Lead Origin_Lead Add Form,Last Activity_SMS Sent,What is your current occupation_Working Professional,Tags_Closed by Horizzon,Tags_Ringing,Tags_Will revert after reading the email,Last Notable Activity_SMS Sent
5820,-0.702065,-0.894255,-1.142797,0,0,0,0,0,1,0
7076,-0.294072,-0.741140,-0.172718,0,1,0,0,0,1,1
8906,0.521912,1.829001,-0.415238,0,0,0,0,0,0,0
3443,-0.090076,-0.768482,-0.415238,0,1,0,0,1,0,1
3017,0.113920,1.243884,0.797361,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
4073,0.929904,-0.622659,2.737519,0,1,0,0,0,1,0
821,1.133900,-0.573443,-0.269726,0,0,0,0,0,1,0
1765,-0.702065,-0.894255,-1.142797,1,1,0,0,0,1,1
8237,-0.498068,0.826463,-0.657758,0,0,0,0,0,0,0
598,-0.090076,0.950414,-0.172718,0,0,0,0,0,1,0

In [45]:
x_train.columns=['TotalVisits', 'Total_Time_Spent_on_Website', 'Page_Views_Per_Visit',
       'Lead_Origin_Lead_Add_Form', 'Last_Activity_SMS_Sent',
       'What_is_your_current_occupation_Working_Professional',
       'Tags_Closed_by_Horizzon', 'Tags_Lost_to_EINS',
       'Tags_Will_revert_after_reading_the_email',
       'Last_Notable_Activity_SMS_Sent']

In [46]:
x_test.columns=['TotalVisits', 'Total_Time_Spent_on_Website', 'Page_Views_Per_Visit',
       'Lead_Origin_Lead_Add_Form', 'Last_Activity_SMS_Sent',
       'What_is_your_current_occupation_Working_Professional',
       'Tags_Closed_by_Horizzon', 'Tags_Lost_to_EINS',
       'Tags_Will_revert_after_reading_the_email',
       'Last_Notable_Activity_SMS_Sent']

In [47]:
x_train.head(3)

,TotalVisits,Total_Time_Spent_on_Website,Page_Views_Per_Visit,Lead_Origin_Lead_Add_Form,Last_Activity_SMS_Sent,What_is_your_current_occupation_Working_Professional,Tags_Closed_by_Horizzon,Tags_Lost_to_EINS,Tags_Will_revert_after_reading_the_email,Last_Notable_Activity_SMS_Sent
4210,0.113920,-0.148732,0.797361,0,0,0,0,0,1,0
3797,0.113920,-0.212530,0.797361,0,0,0,0,0,0,0
9220,0.317916,-0.857799,0.069802,0,1,0,0,0,0,0

# Logistic Regression

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
lr_model = LogisticRegression()
lr_model.fit(x_train,y_train)
lr_pred = lr_model.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,plot_roc_curve

In [51]:
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       0.88      0.93      0.90      1450
           1       0.87      0.78      0.83       860

    accuracy                           0.88      2310
   macro avg       0.87      0.86      0.86      2310
weighted avg       0.88      0.88      0.87      2310

In [52]:
confusion_matrix(y_test,lr_pred)

array([[1349,  101],
       [ 185,  675]])

In [53]:
accuracy_score(y_test,lr_pred)

0.8761904761904762

In [54]:
prob = lr_model.predict_proba(x_test)[:,1]

In [55]:
np.round((prob)*100)

array([16., 68., 36., ..., 98., 16., 54.])

In [56]:
import pickle

In [57]:
# saving the model
pickle.dump(lr_model,open('model.pkl','wb'))

In [58]:
loaded_model=pickle.load(open('model.pkl','rb'))

In [59]:

prediction = loaded_model.predict([[-0.702065,-0.894255,-1.142797,1,1,1,1,1,1,1]])
if prediction[0]==0:
    print('lead was not converted')
else:
    print('lead was converted')

lead was converted

In [60]:
loaded_model.predict_proba([[-0.702065,-0.894255,-1.142797,1,1,1,1,1,1,1]])[:,1][0]*100

99.98356306816683

# THANK YOU...